# Site settings
title: atleeon
email: atleeon@gmail.com
description: > 
  互联网，跑步，读书和摄影。
  IT,Runner,Reading and photography.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://atleeon.com" # the base hostname & protocol for your site
twitter_username: atleeon
github_username:  leeon

# Build settings
markdown: kramdown

paginate: 5

author: Li Yang

gems: [jekyll-paginate]
