auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         1
permalink:        /:categories/:year/:month/:day/:title/

title:            "Octsky"
url:              http://octsky.com
feed:             /feed.xml
author:
    name:         LiYang
    twitter:      twitter.com/realliyang
    key:          octobershiner
description:      "HomePage"
copyright:        "CopryRight LiYang 2012-2012 by GitHub and Jekyll"
headdesc:         "Liyang的博客，记录每一刻"
headkeys:         "李阳,思考,读书,计算机,经济,摄影,音乐,写作"
