markdown:         kramdown
highlighter:      rouge
permalink:        /posts/:title/

title:            "YANG"
url:              http://www.atleeon.com
feed:             /feed.xml
author:
    name:         LiYang
    twitter:      twitter.com/atleeon
    key:          atleeon
description:      "虎口遐想"
copyright:        "CopryRight Liyang 2013-2016 by GitHub and Jekyll"
headdesc:         "leeon 写东西的地方"
headkeys:         "摄影,大数据,推荐系统,数据挖掘,机器学习,数学,读书,电影,音乐"

gems: [jekyll-paginate]

#Baidu analytics / 百度统计(异步的js码，注意使用异步版本的)
baidu_analyze: b89eeb1e30f9da66c71c727631aaa630
